apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: vacdemogit
  labels:
    apps.kubernetes.io/name: spring-petclinic
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-petclinic
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  params:
  - name: live-update
    value: "true"
  source:
    git:
      url: https://github.com/explore-india-booth/spring-tap-petclinic
      ref:
        branch: accelerator
  serviceClaims:
    - name: spring-petclinic-db
      ref:
        apiVersion: v1
        kind: Secret
        name: spring-petclinic-db
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: mysql
  - name: JAVA_TOOL_OPTIONS
    value: >
      -Dspring.devtools.restart.enabled=true
      -Dspring.devtools.restart.poll-interval=2s
      -Dspring.devtools.restart.quiet-period=1s
      -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=9005
